name: Content Writer
on:
  push:
    branches: [ 'main' ]
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
permissions:
  contents: write

jobs:
  blog-post:
    name: Update latest blog post
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pull in rss feed
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://medium.com/feed/@abmmhasan"
  pull-trophy:
    name: Update latest trophy
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - run: curl https://github-readme-stats-git-master-abmmhasan.vercel.app/api?username=abmmhasan&count_private=true&show_icons=true&theme=transparent&include_all_commits=true&hide_title=true&hide_border=true&hide_rank=true > trophy.svg
        - uses: actions/upload-artifact@v3
          with:
            name: my-trophy
            path: trophy.svg