name: Stats
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
permissions:
  contents: write

jobs:
  trophy:
    name: Update latest trophy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
      - name: Commit stats
        continue-on-error: true
        run: wget -U "${UA}" -O "./assets/commitStat.svg" "https://github-readme-stats-git-master-abmmhasan.vercel.app/api?username=abmmhasan&count_private=true&show_icons=true&theme=transparent&include_all_commits=true&hide_title=true&hide_border=false&hide_rank=true"
      - name: Trophy
        continue-on-error: true
        run: wget -U "${UA}" -O "./assets/trophy.svg" "https://github-profile-trophy-abmmhasan.vercel.app/?username=abmmhasan&theme=nord&column=8&margin-w=10&margin-h=15&no-frame=true&rank=SSS,SS,S,AAA,AA,A,B,C,SECRET"
      - name: Streak stats
        continue-on-error: true
        run: wget -U "${UA}" -O "./assets/streak.svg" "https://streak-stats.demolab.com/?user=abmmhasan&theme=transparent&hide_border=false&mode=weekly"
      - name: Commit
        run: |
          if [[ $(git status --porcelain) ]]; then
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .
            git commit -m "${{github.workflow}} (${{github.run_number}}/${{github.run_id}})"
            git push
          else
            echo "nothing to commit"
            exit 0
          fi
