name: Content Writer
on:
  push:
    branches: [ 'main' ]
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
permissions:
  contents: write

jobs:
  trophy:
    name: Update latest trophy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
      - name: Commit stats
        run: wget -U "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36" -O commitStat.svg "https://github-readme-stats-git-master-abmmhasan.vercel.app/api?username%3Dabmmhasan%26count_private%3Dtrue%26show_icons%3Dtrue%26theme%3Dnord%26include_all_commits%3Dtrue%26hide_title%3Dtrue%26hide_border%3Dtrue%26hide_rank%3Dtrue"
      - name: Streak stats
        run: wget -U "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36" -O streak.svg "https://streak-stats.demolab.com?user%3Dabmmhasan%26theme%3Dnord%26hide_border%3Dtrue%26mode%3Dweekly"
      - name: Trophy
        run: wget -U "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36" -O trophy.svg "https://github-profile-trophy-abmmhasan.vercel.app/?username%3Dabmmhasan%26theme%3Dnord%26column%3D7%26margin-w%3D10%26margin-h%3D15%26no-frame%3Dtrue%26rank%3DSSS%2CSS%2CS%2CAAA%2CAA%2CA%2CB%2CC%2CSECRET"
      - name: Commit
        run: |
          if git diff --exit-code; then
            echo "Nothing to commit."
            exit 0
          else
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .
            git commit -m "update"
            git push
          fi
